### ISSUE TITLE
Possible improvements [config-base]

### ISSUE THREAD

**Issue by developer239** [strvcom/code-quality-tools#95] opened 2020-04-28 14:12 UTC
Hello 👋 
a couple of weeks ago (it feels like a long time now 😅) we discussed what we can do to improve STRV code quality tools. This is my first follow up about `eslint-config-base`.

I will share a similar update about `node`, `react`, `react-native`, and `typescript` this week.

**Missing rules:**
I would highly recommend taking a look at everything labeled as **[major]**. 🙂 

- [no-dupe-else-if](https://eslint.org/docs/rules/no-dupe-else-if) error
- [no-import-assign](https://eslint.org/docs/rules/no-import-assign#top) error
- [no-prototype-builtins](https://eslint.org/docs/rules/no-prototype-builtins#top) error
- [no-setter-return](https://eslint.org/docs/rules/no-setter-return#top) ? (right now I have it set as error because I don't do OOP otherwise I would turn it off so that I can write fluent setters)
- [block-scoped-var error](https://eslint.org/docs/rules/block-scoped-var#top) **[major]**
- [complexity](https://eslint.org/docs/rules/complexity#top) (useful but up to discussion how strict we want to have it [‘error’, 5 to 7 seems like good values])
- [grouped-accessor-pairs](https://eslint.org/docs/rules/grouped-accessor-pairs#top) error
- [no-alert](https://eslint.org/docs/rules/no-alert#top) ? error
- [no-constructor-return](https://eslint.org/docs/rules/no-constructor-return#top) error
- [no-div-regex](https://eslint.org/docs/rules/no-div-regex#top) error 
- [no-empty-function](https://eslint.org/docs/rules/no-empty-function#top) ? (not having it at all seems like a good idea)
- [no-eq-null](https://eslint.org/docs/rules/no-eq-null#top) error
- [no-implicit-globals](https://eslint.org/docs/rules/no-implicit-globals#top) error **[major]**
- [no-invalid-this](https://eslint.org/docs/rules/no-invalid-this#top) error 
- [no-param-reassign](https://eslint.org/docs/rules/no-param-reassign#top) error **[major]**
- [no-return-await](https://eslint.org/docs/rules/no-return-await#top) ? error
- [no-useless-catch](https://eslint.org/docs/rules/no-useless-catch#top) error **[major]**
- [no-void](https://eslint.org/docs/rules/no-void#top) ? error (I don't use it so I turned it off)
- [prefer-regex-literals](https://eslint.org/docs/rules/prefer-regex-literals#top) error
- [radix](https://eslint.org/docs/rules/radix#top) error **[major]**
- [init-declarations](https://eslint.org/docs/rules/init-declarations#top) ? (I have this off) 
- [capitalized-comments](https://eslint.org/docs/rules/capitalized-comments#top) (I have this off)
- [max-lines](https://eslint.org/docs/rules/max-lines#top) ? up to discussion how strict we can make this
- [max-lines-per-function](https://eslint.org/docs/rules/max-lines-per-function#top) ? up to discussion how strict we can make this
- [no-bitwise](https://eslint.org/docs/rules/no-bitwise#top) error (personally I would motivate people NOT to use bitwise operators because of what I have seen in Otter.ai)
- [no-multi-assign](https://eslint.org/docs/rules/no-multi-assign#top) error [kind of major for me]
- [no-negated-condition](https://eslint.org/docs/rules/no-negated-condition#top) error **[major]**
- [no-plusplus](https://eslint.org/docs/rules/no-plusplus#top) error **[major]**
- [wrap-regex](https://eslint.org/docs/rules/wrap-regex#top) error 
- [no-useless-rename](https://eslint.org/docs/rules/no-useless-rename#top) erorr
- [prefer-destructuring](https://eslint.org/docs/rules/prefer-destructuring#top) error **[major]**
- [import/no-default-export](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-default-export.md) error **[major]**

**Missing plugins:**
- [absolute-import](https://www.npmjs.com/package/eslint-plugin-absolute-import)
- [unused-imports](https://www.npmjs.com/package/eslint-plugin-unused-imports) **[major]**

**Missing rules from missing plugins:**
- absolute-import/no-relative-path warning **[major]**
- unused-imports/no-unused-imports error **[major]**
- unused-imports/no-unused-vars error **[major]**

**Rules that can be more strict:**
- [import-order see comment bellow](https://github.com/strvcom/code-quality-tools/issues/95#issuecomment-623407660)
- [no-loop-func](https://eslint.org/docs/rules/no-loop-func#top) error
- [no-unused-vars](https://eslint.org/docs/rules/no-unused-vars#top) this can be off when we use  unused-imports plugin
- [no-new-object](https://eslint.org/docs/rules/no-new-object#top) error **[major]**
- [no-template-curly-in-string](https://eslint.org/docs/rules/no-template-curly-in-string#top) error
- [no-unmodified-loop-condition](https://eslint.org/docs/rules/no-unmodified-loop-condition#top) error
- [no-useless-concat](https://eslint.org/docs/rules/no-useless-concat#top) error
- [no-useless-return](https://eslint.org/docs/rules/no-useless-return#top) error **[major]**
- [prefer-spread](https://eslint.org/docs/rules/prefer-spread#top) error **[major]**
- [require-await](https://eslint.org/docs/rules/require-await#top) error (this fall in the group with `no-return-await` I saw `async` keyword being misused, essentially it changes the function to promise for no reason I believe that is a bad practice)
- [vars-on-top](https://eslint.org/docs/rules/vars-on-top#top) error **[major]**
- [no-console](https://eslint.org/docs/rules/no-console#top) error **[major]**
- [func-names](https://eslint.org/docs/rules/no-console#top) error
- [no-undefined](https://eslint.org/docs/rules/no-undefined#top) 0 (actually I turned this off as I prefer [undefined over null](https://github.com/microsoft/TypeScript/wiki/Coding-guidelines))
- [symbol-description](https://eslint.org/docs/rules/symbol-description#top) error
- [import/no-duplicates](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md) error **[major]**

**Rules that I would change:**

- pretty much everything can be set as `error`
- **if we want to be consistent then code style issues shouldn't make it to GitHub**
- I see no value in warnings. When we as a team decide which rules are important we should follow these rules. 🙂 
- Personally I use `warn` only for rules that I know I shouldn't break but sometimes I have to (no-console, ban-ts-ignore, camelcase [because of graphql code gen], ...)

**Comment by robertrossmann** [comment] 2020-04-28 15:11
@developer239 Thanks for all these suggestions! I will look through them in the coming days.

Right now I can tell you this much:

Stylistic rules and rules where we cannot with a high certainty say that the code is invalid/bad/wrong in any way shall never cause ESLint to fail with non-zero exit code. This was by design from day 1. It's the only reason why we have `semi` rule set to `warn`. 🤷‍♂️ 😇 I know it may seem counter-intuitive, but there are many situations where you really want to ie. use template curlies in a plain string (Sendgrid templates) or you want to make a function explicitly an async function because that's how you design the public API, even though there is no asynchronous work being done in it yet.

If you really want to be the evil dictator, you can always run ESLint with `--max-warnings 0` flag on a CI server -> any warning will fail the CI.

And I feel that some other rules mentioned in your *Missing rules* list are enabled in the ruleset somewhere; are you sure they are missing? 🤔 I will take a look. Some of them look like we should have them.

**Comment by developer239** [comment] 2020-04-29 13:20
@robertrossmann Honestly, I don't mind I just wanted to share my opinion here. 🙂 

How I can help right now is I can find rules that we are missing and add them to the config. I created a tool that compares my eslint config with STRV config programmatically. I didn't check all rules myself but I am 99 % sure that rules that I shared here are actually missing in STRV config.

https://github.com/developer239/compare-linters

**Comment by xhudec** [comment] 2020-05-04 10:42
Great suggestions @developer239!

I agree with @robertrossmann that only an **invalid/bad/wrong** code should fail with a non-zero exit code. Others should be considered as a warning saying something smelly is present.

## Labeled as `major`

- [`block-scoped-var`](https://eslint.org/docs/rules/block-scoped-var#top)
    - agree
- [`no-implicit-globals`](https://eslint.org/docs/rules/no-implicit-globals#top)
    - agree
- [`no-param-reassign`](https://eslint.org/docs/rules/no-param-reassign#top)
    - agree
- [`no-useless-catch`](https://eslint.org/docs/rules/no-useless-catch#top)
    - agree
- [`radix`](https://eslint.org/docs/rules/radix#top)
    - agree
    - `warn` should be enough
- [`no-multi-assign`](https://eslint.org/docs/rules/no-multi-assign#top)
    - totally agree
- [`no-negated-condition`](https://eslint.org/docs/rules/no-negated-condition#top)
    - agree
    - `warn` should be enough
- [`no-plusplus`](https://eslint.org/docs/rules/no-plusplus#top)
    - agree
    - with option `allowForLoopAfterthoughts: true` 🤔
- [`prefer-destructuring`](https://eslint.org/docs/rules/prefer-destructuring#top)
    - agree
    - `warn` should be enough
- [`import/no-default-export`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-default-export.md)
    - disagree - too opinionated I would say
    - or another solution might to move it among  `style` rules
    - I agree that with default exports devs sometimes import and "rename" the imported thingy, which is unfortunate and causes inconsistencies which are tricky especially while refactoring something, but let's be honest, most of us use default exports nowadays.

## Others

- [`no-dupe-else-if`](https://eslint.org/docs/rules/no-dupe-else-if)
    - agree
    - `warn` should be enough
- [`no-import-assign`](https://eslint.org/docs/rules/no-import-assign#top)
    - agree
- [`no-prototype-builtins`](https://eslint.org/docs/rules/no-prototype-builtins#top)
    - agree
- [`no-setter-return`](https://eslint.org/docs/rules/no-setter-return#top)
    - 🤷‍♂️
- [`complexity`](https://eslint.org/docs/rules/complexity#top)
    - agree
    - with levels 5-7, as @developer239 suggested 
- [`grouped-accessor-pairs`](https://eslint.org/docs/rules/grouped-accessor-pairs#top)
    - agree
    - should be located among `style` rules
- [`no-alert`](https://eslint.org/docs/rules/no-alert#top)
    - agree
- [`no-constructor-return`](https://eslint.org/docs/rules/no-constructor-return#top)
    - agree
- [`no-div-regex`](https://eslint.org/docs/rules/no-div-regex#top)
    - agree
    - should be colocated with `optional` or `style` rulesets?
- [`no-empty-function`](https://eslint.org/docs/rules/no-empty-function#top)
    - agree
    - `warn` should be enough
- [`no-eq-null`](https://eslint.org/docs/rules/no-eq-null#top)
    - agree
    - might be too strict - so `optional` ruleset?
    - this might already be handled by `eqeqeq` rule, right?
- [`no-invalid-this`](https://eslint.org/docs/rules/no-invalid-this#top)
    - agree
- [`no-return-await`](https://eslint.org/docs/rules/no-return-await#top)
    - 🤔I remember that there was some discussion on our #dev channel on this topic
- [`no-void`](https://eslint.org/docs/rules/no-void#top)
    - agree
- [`prefer-regex-literals`](https://eslint.org/docs/rules/prefer-regex-literals#top)
    - agree
    - `warn` should be enough
- [`init-declarations`](https://eslint.org/docs/rules/init-declarations#top)
    - agree
    - `optional` ruleset
- [`capitalized-comments`](https://eslint.org/docs/rules/capitalized-comments#top)
    - agree
    - `style` ruleset
- [`max-lines`](https://eslint.org/docs/rules/max-lines#top)
    - agree if configured properly
    - `warn` should be enough
    - `optional` or `style` rulesets?
- [`max-lines-per-function`](https://eslint.org/docs/rules/max-lines-per-function#top)
    - agree if configured properly
    - `warn` should be enough
    - `optional` or `style` rulesets?
- [`no-bitwise`](https://eslint.org/docs/rules/no-bitwise#top)
    - agree
- [`wrap-regex`](https://eslint.org/docs/rules/wrap-regex#top)
    - 🤷‍♂️
    - `style` ruleset?
- [`no-useless-rename`](https://eslint.org/docs/rules/no-useless-rename#top)
    - agree
    - `optional` ruleset?

## Missing plugins

- `eslint-plugin-absolute-import`
    - Wouldn't proper *path aliases* be a better solution?
    - In my opinion, this is way too dependent on project setup
    - Also, the repo has 0 stars so it is not yet used too much, I would honestly wait with integrating this into our toolbelt
- `eslint-plugin-unused-imports`
    - If I understand, correctly the purpose of this plugin is the auto-fixer feature for unused imports? If not I don't see any added value as `no-unused-vars` and `no-unused-imports` does the thing, right?

cc @dannytce

**Comment by developer239** [comment] 2020-05-04 11:19
Thanks @xhudec for taking your time to review this. 🙂 

I pretty much agree with everything you said. Maybe we can keep `radix` as `error` because it is easily fixable and the codebase will be more consistent.

About the plugins though:

- `eslint-plugin-absolute-import`
  - Now it has 1 star 😄 the purpose of the plugin is to `warn` or `error` whenever we use relative import in the project. It is not project dependent. It is not auto-fixable but the effort is worth it.

![image](https://user-images.githubusercontent.com/14946081/80959844-f08e6300-8e07-11ea-82a4-0b94822a8e9e.png)

- `eslint-plugin-unused-imports`
  - Honestly, I don't remember why I started using this thing. 🤔 It can remove unused import automatically. `no-unused-imports` rule does not exist. But you are right that `no-unused-vars` warns about the same issue - although it is not auto-fixable.

**Comment by developer239** [comment] 2020-05-04 11:25
**ONE MORE ISSUE FROM ME**

- it is auto-fixable

```
'import/order': [
  'error',
  {
    'groups': ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
    'alphabetize': {
      'order': 'asc',
      'caseInsensitive': true,
    },
  },
],
```

🤤 
![image](https://user-images.githubusercontent.com/14946081/80961212-c12d2580-8e0a-11ea-9fee-c548f3199014.png)

**Comment by robertrossmann** [comment] 2020-10-08 22:59
Thanks for all the feedback! ❤️ I went through the first section of the rules (_ Missing rules_) and added some here: 471568f2fddce960e200a9d6ed796f3f777d2c21. For the ones I did not add, I list my reasoning below. I will try to go through the rest sometime soon. 💪 

- `no-prototype-builtins`: too restrictive
- `block-scoped-var`: `var` declarations are already forbidden via rule
- `complexity`: too restrictive
- `no-alert`: too restrictive, `alert` or `prompt` are quite generic function names and having them flagged in Node.js for no reason is not desireable
- `no-constructor-return`: Haha, no. 😂 This one's fun - you can return something from a class constructor and whatever you return will be the result of calling `new`. You can completely bend the returned thing. Very fun, indeed.
- `no-div-regex`: the thing it tries to "un-confuse" is not confusing at all
- `no-empty-function`: too restrictive
- `no-eq-null`: we already require strict comparisons to be used
-  `no-implicit-globals`: Node.js and I believe most modern frontend bundlers already wrap the code in an IIFE so this is redundant and quite restrictive
- `no-invalid-this`: I tried personally, very restrictive. It's enabled for TypeScript, though 💡
- `no-param-reassign`: I tried personally, very restrictive
- `no-return-await`: you **should** use `return await` constructs. The performance hazards mentioned in rule docs have been optimised away in recent V8 releases, plus, if you do this, V8 can properly construct an async stack trace when errors occur, substantially improving developer UX (or is it DX, then? 🤔). See https://v8.dev/blog/fast-async and https://v8.dev/docs/stack-trace-api
- `no-void`: `void` is awesome, it helps you avoid semicolons 😇 and allows several other tricks.
- `init-declarations`: too restrictive
- `capitalized-comments`: conflicts with `eslint-disable-*` and other `@ts-*` comment directives 🤷‍♂️ 
- `max-lines` & `max-lines-per-function`: I tried, too restrictive
- `no-bitwise`: why? They are very useful.
- `no-negated-condition`: too restrictive. Sometimes you want to take the shorter, falsey path first, or it is simply easier to read when the cond is negated
- `no-plusplus`: just learn how ASI works 🤷‍♂️ _(I can explain if you are interested, I am a huge ASI fan, as you surely know 😇)_
- `wrap-regex`: ...but why. It looks very clear to me even without the wrap.
- `prefer-destructuring`: I tried, too restrictive. Sometimes it resulted in code that was worse/more difficult to read.
- `import/no-default-export`: yeaaaah I'm with you on this one, but no. 😇 It's too restrictive for quite a large population of developers, sadly.

**Comment by robertrossmann** [comment] 2020-10-09 08:59
I checked out the other rules where you mention you would increase the severity to `error`.

For almost all rules there is a possibility that the rule would flag some valid piece of code which would cause a potentially working code to be rejected by CI. This is highly undesireable. I will mention a few rules below where I believe some explanation might be helpful as to why it should not be used/set to `error`.

- `require-await`: Declaring a function as `async` changes the runtime semantics of that function (ie. it will never `throw`, it can only ever return a rejected promise). In some situations it is beneficial to declare a function as `async` even though it could be sync today, if you know that there is a high chance you will need to do async work inside it in the future. This way you can future-proof your public API if you work on a library or some other reusable component.
- `no-template-curly-in-string`: Some libraries, sadly, use `${}` syntax as a templating language. Setting this rule to `error` would flag potentially working and valid code as error.

Most of the other rules are cosmetic/stylistic preferences and therefore should be defined as warnings.

> Fun fact: in the past, the original ruleset used to have all those various `max-lines-per-function`, `complexity` and other similar rules enabled. You should have seen the haters coming at me from all corners of the office. 🔥 And they were right. The intention might be good (to write easy-to-follow code with not too many branches) but in practice these rules could not get you there; proper code reviews are what can help us write easy-to-follow code. 🕵️ 

**Missing plugins:**

As for `eslint-plugin-unused-imports`, I see no added value here. Most of the use cases can be attained with `no-unused-vars` and similar.
And with `eslint-plugin-absolute-import` you would kill a very powerful feature of Node.js so that's a no go. There are situations where you really want to use a relative file path instead of an absolute one, ie. when you create a piece of functionality which should behave like a single unit but actually consists of many parts, and you want to keep those many parts hidden from the rest of the codebase. Those relative imports would always have to be moved together, as a single unit, so there is no point in having an absolute import path for them.

Anyway, thank you so much for taking the time to review the ruleset! I incorporated a lot of your proposed changes, even if with a lower severity level. 😇 ❤️

**Closed by robertrossmann** 2020-10-09 08:59 UTC
Labels: enhancement
